### ISSUE TITLE
NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys

### ISSUE THREAD

**Issue by Plato2013** [kennedyoliveira/ultimate-pastebin-intellij-plugin#2]
Installed the Plugin within PHPStorm 10.0.3 on a mac I get the following error:

`NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys`

when clicking on 'Create Paste' in the context menu.

**Comment by kennedyoliveira** [comment]
Hello @Plato2013, what version of the plugin did you install?

**Comment by Plato2013** [comment]
Hi,
I've installed it using the plugin browser within the IDE. According to that it is v1.3.1.0

**Comment by kennedyoliveira** [comment]
@Plato2013, thank you! I'll check what's happening

**Comment by kennedyoliveira** [comment]
hey @Plato2013 , i found out the problem, fixed and updated to v1.3.1.1, just check for updates in your IDE and it should tell you there is a new version, and tell me if it's worked for you!

If not appear, maybe need to way sometime, because i had some trouble updating the plugin in JetBrains repository, i think they are having issues and maybe can stop working for maintenance of something.

**Comment by kennedyoliveira** [comment]
Just after i wrote to you i saw the really is down for maintanence haha, so after they come back you can update your plugin and it should work fine.

Waiting your feedback :D

![jetbrains_maintenance](https://cloud.githubusercontent.com/assets/7723330/13707705/a8461634-e789-11e5-973e-0ba5a2af89d4.png)

**Comment by kennedyoliveira** [comment]
@Plato2013, did you try the new version? It solved the problem?

**Comment by Plato2013** [comment]
Hello,

I've updated it and now everything seems to work. Thank you for the fast replies and fast fix!
